name: CI-Polaris
on:
  push:
    branches: [ main, master, develop, stage, release , SIGINT-2209]
  pull_request:
    branches: [ main, master, develop, stage, release ]
  workflow_dispatch:
    
jobs:
  build:
    runs-on: [ macOS ]
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3
      - name: Black Duck SCA Scan
        uses: blackduck-inc/blackducksecurityscan@main 
       
        with:
          ### SCANNING: Required fields
          #blackducksca_url: ${{ vars.BLACKDUCK_URL }}
          #blackducksca_token: ${{ secrets.BLACKDUCK_TOKEN }}
          #
         
          ### SCANNING: Optional fields
          # blackducksca_scan_failure_severities: 'BLOCKER,CRITICAL'
          
          ### FIX PULL REQUEST CREATION: Uncomment below to enable
          # blackducksca_fixpr_enabled: true
          # github_token: ${{ secrets.GITHUB_TOKEN }} # Required when Fix PRs is enabled
          
          ### PULL REQUEST COMMENTS: Uncomment below to enable
          # blackducksca_prcomment_enabled: true 
          # github_token: ${{ secrets.GITHUB_TOKEN }} # Required when PR comments is enabled

          ### SARIF report generation and upload to GitHub Adavanced Security: Uncomment below to enable
          # blackducksca_reports_sarif_create: true # Create Black Duck SCA SARIF report and upload it as artifact
          # blackducksca_upload_sarif_report: true  # Upload Black Duck SCA SARIF report in GitHub Advanced Security tab
          # github_token: ${{ secrets.GITHUB_TOKEN }} # Required when blackducksca_upload_sarif_report is set as true
          srm_url: ${{ vars.SRM_URL }}
          srm_apikey: ${{ secrets.SRM_API_KEY }}
          srm_assessment_types: "SCA,SAST"
