name: CI-SRM
on:
  push:
    branches: [ main, master, develop, stage, release ]
  workflow_dispatch:
jobs:
  build:
    runs-on: [ self-hosted ]
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3
      - name: SRM Scan
        uses: synopsys-sig/synopsys-action@SIGINT-864
        with:
          ### SCANNING: Required fields
          srm_url: ${{ vars.SRM_URL }}
          srm_apikey: ${{ secrets.SRM_API_KEY }}
          srm_assessment_types: "SCA,SAST"

          ### SCANNING: Optional fields
          # srm_project_name: ${{ vars.PROJECT_NAME }}
          # srm_project_id: ${{ vars.PROJECT_ID }}
          # srm_branch_name: ${{ vars.BRANCH_NAME }}
          # srm_branch_parent: ${{ vars.BRANCH_PARENT }}
          srm_waitForScan: false   # Used to support the async mode 
          # blackduck_execution_path: ${{ vars.BLACKDUCK_EXECUTION_PATH }}
          # coverity_execution_path: ${{ vars.COVERITY_EXECUTION_PATH }}    
          # project_directory: ${{ vars.PROJECT_DIRECTORY }}
          
          ### Uncomment below to add arbitrary CL parameters
          # blackduck_search_depth: 2
          # blackduck_args: '--detect.diagnostic=true'
          # blackduck_config_path: '/Users/Config/application.properties'
          # coverity_build_command: mvn clean install
          # coverity_clean_command: mvn clean
          # coverity_config_path: /Users/Config/coverity.yml
          # coverity_args: --config-override capture.build.build-command=mvn install
